# These are some functions inspired by the Linux kernel build system.
# They are used to possibly hide details of compilation.
# if CONFIG_RTAI_QUITE variable is defined to quiet_, it would show short messages.

# Convenient variables
squote  := '

###
# Escape single quote for use in echo statements
escsq = $(subst $(squote),'\$(squote)',$1)

# print and execute commands
cmd = @echo '  $(call escsq,$(quiet_cmd_$(1)))'; $(cmd_$(1))
