#!/bin/sh
prefix=`rtai-config --prefix`

if test "$prefix" = ""; then
echo "ERROR: please set your PATH variable to <rtai-install>/bin"
exit
fi

MODULES=$prefix/modules

echo
echo "*** A METTLEY OF LATENCY MEASUREMENTs (user, kernel, kernel timers) ***"
echo "Press <enter> to load modules:"
read junk
cd ..; ./ldmod; cd -
#if (`rtai-config --linux-version | grep -q 2.6`);
#then insmod $MODULES/rtai_tasklets.ko;
#else insmod $MODULES/rtai_tasklets.o; fi
if (`rtai-config --linux-version | grep -q 2.6`);
then insmod $MODULES/rtai_rtdm.ko; insmod ./timerbench_rt.ko
else insmod $MODULES/rtai_rtdm.o; insmod ./timerbench.o; fi
sync
echo
echo "Now start your realtime test of choice <enter>,"
echo "<ctrl-C> to end it:>"
read junk
./latency -p 40 -t $1
sync
echo
echo "Done. Press <enter> to remove the modules."
read junk
./rem
