#include "/home/mante/scilab-2.6/routines/machine.h"
/* Code prototype for standalone use  */
/*     Generated by Code_Generation toolbox of Scicos with scilab-2.6 */
/*     date : 10-Dec-2002 */

#include <stdio.h>
#include <string.h>

#include <sys/types.h>
#include <sys/mman.h>
#include <math.h>

#define KEEP_STATIC_INLINE
#include <rtai_lxrt_user.h>
#include <rtai_lxrt.h>

void pidmain1(double *z, double *t, double * rpar, integer *nrpar,
   integer *ipar, integer *nipar);

void pidmain2(double *z, double *t, double * rpar, integer *nrpar,
   integer *ipar, integer *nipar) ;

void pid_init(double *z, double *t, double * rpar, integer *nrpar,
   integer *ipar, integer *nipar) ;

void pid_end(double *z, double *t, double * rpar, integer *nrpar,
   integer *ipar, integer * nipar) ;

void pid_const_update(double *z, double *t, double * rpar,
   integer *nrpar, integer *ipar, integer * nipar) ;

void set_nevprt(int nevprt);

static double RPAR1[ ] = {1,0,-1,1,2,0,1,0,0.01,0,-1,1,1,60,10,10,0,1,
  -1,1,1,1,1,1,-1,9.99,1.0001,-1.001,0.00001,1.00001,0};
static integer NRPAR1  = 31;
static integer IPAR1[ ]= {1,3,1,4,1,2,0};
static integer NIPAR1  = 7;

static double z[]={0,0,0,0,0,1,4.538E+08,0.2113249,9.99,0,0,0,0,0,0,0,
  0,0,0,0,0,0,0,1.0001,1,1.0001,-0.2115483,0.2113370,0,0,0,0,0,0,0,0,0,
  0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0};

/*----------------------------------------  Lapack messag function */
void
C2F(xerbla)(SRNAME,INFO,L)
char *SRNAME;
int *INFO;
long int L;
{
printf("** On entry to %s, parameter number %d had an illegal value\n",SRNAME,*INFO);
}

#include "pid_io.c"
