EXTRA_CFLAGS += -I$(rtai_srctree)/base/include \
		-I$(rtai_srcdir) \
		-I$(src)/../../../base/include \
		-I$(src)/../../.. \
		-D__IN_RTAI__

obj-m += rtai_serial.o

rtai_serial-objs := $(rtai_objs)
