#!/bin/sh
if [ $UID != 0 ]; then SUDO="sudo "; else SUDO=""; fi
echo
echo "*** PRIORITY INHERITANCE CHECK FOR RES-SEM and INTERTASK MSG(kernel) ***"
echo "Press <enter> to load modules:"
read junk
cd ..; ./ldmod; cd -
if [ "$1" != "" ];then
	semtype="SemType=$1"
fi
echo
echo "Now start the realtime process <enter>,"
read junk
echo "Example 1, type <return> to continue"
read junk
if (`rtai-config --linux-version | grep -q 2.6`);
then insmod ./prioinher1_rt.ko $semtype;
else insmod ./prioinher1.o $semtype; fi
echo " "
echo "Press <enter> to remove the modules."
read junk
rmmod prioinher1_rt
rmmod prioinher1
echo "Example 2, type <return> to continue"
read junk
if (`rtai-config --linux-version | grep -q 2.6`);
then insmod ./prioinher2_rt.ko $semtype;
else insmod ./prioinher2.o $semtype; fi
echo " "
echo "Done. Press <enter> to remove the modules."
read junk
rmmod prioinher2_rt
rmmod prioinher2
./rem
