#!/bin/sh
if [ $UID != 0 ]; then SUDO="sudo "; else SUDO=""; fi
echo
echo "*** CHECK TSCs SYNCHRONISATION (to get an idea on how bad/good it is) ***"
echo "Press <enter> to load modules:"
read junk
sync
sync
sync
if (`rtai-config --linux-version | grep -q 2.6`);
then insmod ./testscsync_rt.ko;
else insmod ./testscsync.o; fi
echo
echo "Done. Press <enter> to remove the modules."
read junk
rmmod testscsync_rt
