EXTRA_CFLAGS += -I$(rtai_srctree)/base/include \
		-I$(src)/../../../include \
		-I$(src)/../../../.. \
		-D__IN_RTAI__

EXTRA_AFLAGS += -I$(rtai_srctree)/base/include \
		-I$(src)/../../../include \
		-I$(src)/../../../.. \
		-D__IN_RTAI__

obj-m += rtai_hal.o

rtai_hal-objs := $(rtai_objs)
