#!/bin/sh
if [ $UID != 0 ]; then SUDO="sudo "; else SUDO=""; fi
echo
echo "*** ROUND ROBIN SCHEDULING (kernel) ***"
echo "Press <enter> to load modules:"
read junk
cd ..; ./ldmod; cd -
echo
echo "Now start the realtime process <enter>:"
read junk
sync
if (`rtai-config --linux-version | grep -q 2.6`);
then insmod ./rndrob_rt.ko;
else insmod ./rndrob.o; fi
echo
echo "Done. Press <enter> to remove the modules."
read junk
./rem
