#!/bin/sh
#!/bin/sh

prefix=`rtai-config --prefix`

if [ "$prefix" == "" ]; then
echo "ERROR: please set your PATH variable to <rtai-install>/bin"
exit
fi

MODULES=$prefix/modules

if [ $UID != 0 ]; then SUDO="sudo "; else SUDO=""; fi
echo
echo "*** BASE REMOTE RTAI SERVICEs DEMONSTRATOR (kernel) ***"
echo "Press <enter> to load modules:"
read junk
cd ..; ./ldmod; cd -
echo
echo "Now start the realtime process <enter> and wait for its end."
read junk
sync
if [`rtai-config --linux-version | grep -q 2.6` -o `rtai-config --linux-version | grep -q 3.`];
then

insmod $MODULES/rtai_netrpc.ko ThisNode="127.0.0.1";
sync
insmod ./comnode_rt.ko;
insmod ./task_code_rt.ko ComNode="127.0.0.1";
insmod ./start_task_rt.ko ComNode="127.0.0.1" TaskNode="127.0.0.1";

else

insmod $MODULES/rtai_netrpc.o ThisNode="127.0.0.1";
sync
insmod ./comnode.o;
insmod ./task_code.o ComNode="127.0.0.1";
insmod ./start_task.o ComNode="127.0.0.1" TaskNode="127.0.0.1";

fi

echo
echo "Done. Press <enter> to remove the modules."
read junk
./rem
