EXTRA_CFLAGS += -I$(rtai_srctree)/base/include \
		-I$(rtai_srctree)/addons/rtdm \
		-I$(src)/../../include \
		-I$(src)/../../.. \
		$(rtai_extradef) \
		-D__IN_RTAI__

obj-m += rtai_netrpc.o

rtai_netrpc-objs := $(rtai_objs)
