#!/bin/sh

prefix=`rtai-config --prefix`
arch=`rtai-config --arch`
insmod=/sbin/insmod

MODULES=$prefix/modules

sync
if [ $UID != 0 ]; then SUDO="sudo "; else SUDO=""; fi
echo
echo "*** RAW IRQ LATENCY CHECKER ***"
echo "Press <enter> to load modules then ..."
read junk

if [ "$prefix" == "" ]; then
echo "ERROR: please set your PATH variable to <rtai-install>/bin"
exit
fi
if [`rtai-config --linux-version | grep -q 2.6` -o `rtai-config --linux-version | grep -q 3.`];
then $insmod $MODULES/rtai_hal.ko; insmod ./irqlat_rt.ko;
else $insmod $MODULES/rtai_hal.o; insmod ./irqlat.o; fi
echo
read junk
#./rem
