#!/bin/sh

prefix=`rtai-config --prefix`

if [ "$prefix" == "" ]; then
echo "ERROR: please set your PATH variable to <rtai-install>/bin"
exit
fi

libpath=`rtai-config --library-dir`

if [ "$libpath" == "" ]; then
echo "ERROR: please set your PATH variable to <rtai-install>/bin"
exit
fi

export LD_LIBRARY_PATH=$libpath:$LD_LIBRARY_PATH

MODULES=$prefix/modules

if [ $UID != 0 ]; then SUDO="sudo "; else SUDO=""; fi
echo
echo "*** RTDM MMAP TEST (user) ***"
echo "Press <enter> to load modules:"
read junk
cd ../..; ./ldmod; cd -
echo
echo "Now start the realtime process <enter>."
read junk
sync
if (`rtai-config --linux-version | grep -q 2.6`);
then 
insmod $MODULES/rtai_rtdm.ko
insmod ./realtimedriver_rt.ko;
else 
insmod $MODULES/rtai_rtdm.o
insmod ./realtimedriver.o; 
fi
$SUDO ./user
echo
echo "Done. Press <enter> to remove the modules."
read junk
./rem
