#!/bin/sh
if [ $UID != 0 ]; then SUDO="sudo "; else SUDO=""; fi
echo
echo "*** EDF SCHEDULING (kernel space) ***"
echo "Press <enter> to load modules:"
read junk
cd ..; ./ldmod; cd -
echo
echo "Now start the realtime process <enter>, <enter> again to end it."
read junk
sync
if [`rtai-config --linux-version | grep -q 2.6` -o `rtai-config --linux-version | grep -q 3.`];
then insmod ./edf_rt.ko;
else insmod ./edf.o; fi
echo
echo "Done. Press <enter> to remove the modules."
read junk
./rem
