#!/bin/sh

prefix=`rtai-config --prefix`

if [ "$prefix" == "" ]; then
echo "ERROR: please set your PATH variable to <rtai-install>/bin"
exit
fi

MODULES=$prefix/modules

if [ $UID != 0 ]; then SUDO="sudo "; else SUDO=""; fi
echo
echo "*** BASIC TASKLETs (kernel) ***"
echo "Press <enter> to load modules:"
read junk
cd ..; ./ldmod; cd -
echo
echo "Now start the realtime process <enter> and wait for its end."
read junk
sync
if (`rtai-config --linux-version | grep -q 2.6`);
then insmod $MODULES/rtai_tasklets.ko; insmod ./ktest_rt.ko;
else insmod $MODULES/rtai_tasklets.o; insmod ./ktest.o; fi
echo
echo "Done. Press <enter> to remove the modules."
read junk
./rem
