EXTRA_CFLAGS += -I$(rtai_srctree)/base/include \
		-I$(src)/../../../include \
		-I$(src)/../../../.. \
		-D__IN_RTAI__

obj-m += $(rtai_target).o

rtai_calibrate-objs := $(rtai_objs)
rtai_smi-objs := $(rtai_objs)
