#!/bin/sh

prefix=`rtai-config --prefix`

if [ "$prefix" == "" ]; then
echo "ERROR: please set your PATH variable to <rtai-install>/bin"
exit
fi

export PYTHONPATH=$prefix/rtai-py

libpath=`rtai-config --library-dir`

if [ "$libpath" == "" ]; then
echo "ERROR: please set your PATH variable to <rtai-install>/bin"
exit
fi

export LD_LIBRARY_PATH=$libpath:$LD_LIBRARY_PATH

if [ $UID != 0 ]; then SUDO="sudo "; else SUDO=""; fi
echo
echo "*** BITSTEST (user) ***"
echo "Press <enter> to load LXRT modules:"
read junk
cd ../; ./ldmod; cd -
echo
echo "Now start the realtime process <enter>:"
read junk
python bitstest.py
echo
echo "Done. Press <enter> to remove the modules."
read junk
../remod
