#!/bin/sh

libpath=`rtai-config --library-dir`

if [ "$libpath" == "" ]; then
echo "ERROR: please set your PATH variable to <rtai-install>/bin"
exit
fi

export LD_LIBRARY_PATH=$libpath:$LD_LIBRARY_PATH

if [ $UID != 0 ]; then SUDO="sudo "; else SUDO=""; fi
echo
echo "*** SOMETHING THAT SHOULD WORK LIKE A METALS PRESS (user) ***"
echo "Press <enter> to load modules:"
read junk
cd ../..; ./ldmod; cd -
echo
echo "Now start the realtime process <enter>."
read junk
sync
if (`rtai-config --linux-version | grep -q 2.6`);
then insmod ./handler_rt.ko;
else insmod ./handler.o; fi
$SUDO ./press < pdata
echo
echo "Done. Press <enter> to remove the modules."
read junk
./rem
