#!/bin/sh

prefix=`rtai-config --prefix`

if test "$prefix" = ""; then
echo "ERROR: please set your PATH variable to <rtai-install>/bin"
exit
fi

libpath=`rtai-config --library-dir`
export LD_LIBRARY_PATH=$libpath:$LD_LIBRARY_PATH

MODULES=$prefix/modules

echo
echo "*** SOUND USING REMOTE INTERTASK MSGes (user) ***"
echo "Press <enter> to load modules:"
read junk
cd ../..; ./ldmod; cd -
sync
if [`rtai-config --linux-version | grep -q 2.6` -o `rtai-config --linux-version | grep -q 3.`];
then insmod $MODULES/rtai_netrpc.ko ThisNode="127.0.0.1";
else insmod $MODULES/rtai_netrpc.o ThisNode="127.0.0.1"; fi
echo
echo "Now start the realtime process <enter>,"
echo "Press <enter> when you want to end it."
read junk
./speaker1 &
until(`ps -a | grep -q speaker1`); do sleep 1; done
./player SpkNode="127.0.0.1"
while(`ps -a | grep -q speaker1`); do sleep 1; done
echo
echo "Done. Press <enter> to remove the modules."
read junk
./rem
