#!/bin/sh

libpath=`rtai-config --library-dir`

if [ "$libpath" == "" ]; then
echo "ERROR: please set your PATH variable to <rtai-install>/bin"
exit
fi

export LD_LIBRARY_PATH=$libpath:$LD_LIBRARY_PATH

if [ $UID != 0 ]; then SUDO="sudo "; else SUDO=""; fi
echo
echo "*** 2 INTERACTING TASKS USING MANY RTAI APIs WHILE FLOODING HARD/SOFT/HARD ***"
echo "Press <enter> to load LXRT modules:"
read junk
cd ..; ./ldmod; cd -
echo
echo "Now start the realtime process <enter>:"
read junk
$SUDO ./master
#while(`ps -a | grep -q slave`); do sleep 1; done
#while(`ps -a | grep -q master`); do sleep 1; done
echo
echo "Done. Press <enter> to remove the modules."
read junk
read junk
../remod
