#!/bin/sh

prefix=`rtai-config --prefix`

if [ "$prefix" == "" ]; then
echo "ERROR: please set your PATH variable to <rtai-install>/bin"
exit
fi

libpath=`rtai-config --library-dir`
if [ "$libpath" == "" ]; then
echo "ERROR: please set your PATH variable to <rtai-install>/bin"
exit
fi
export LD_LIBRARY_PATH=$libpath:$LD_LIBRARY_PATH

MODULES=$prefix/modules

if [ $UID != 0 ]; then SUDO="sudo "; else SUDO=""; fi
echo
echo "*** A TEST OF THE RTAI SERIAL DRIVER ***"
echo "Press <enter> to load modules:"
read junk
setserial /dev/ttyS0 uart none
setserial /dev/ttyS1 uart none
setserial /dev/ttyS0 uart 16550A
setserial /dev/ttyS1 uart 16550A
setserial /dev/ttyS0 uart none
setserial /dev/ttyS1 uart none
cd ..; ./ldmod; cd -
if (`rtai-config --linux-version | grep -q 2.6`);
then
insmod $MODULES/rtai_serial.ko #spconfig=0x3f8,4,0x2f8,3
else
insmod $MODULES/rtai_serial.o #spconfig=0x3f8,4,0x2f8,3
fi

echo
echo "Now start the realtime process <enter> and wait for its end."
read junk
sync
$SUDO ./serial
echo
echo "Done. Press <enter> to remove the modules."
read junk
./rem
