#!/bin/sh

libpath=`rtai-config --library-dir`

if [ "$libpath" == "" ]; then
echo "ERROR: please set your PATH variable to <rtai-install>/bin"
exit
fi

export LD_LIBRARY_PATH=$libpath:$LD_LIBRARY_PATH

if [ $UID != 0 ]; then SUDO="sudo "; else SUDO=""; fi
echo
echo "*** TESTs MQUEUEs and SEMs (user) ***"
echo "Press <enter> to load LXRT modules:"
read junk
cd ../; ./ldmod; cd -
#insmod /usr/magma/modules/rtai_tasklets.ko
echo
echo "Now start the realtime process <enter>:"
read junk
$SUDO ./cyclictest -n -Q -d0 -t8 -p99 -c1 -i100
#$SUDO ./cyclictest  --h
echo
echo "Done. Press <enter> to remove the modules."
read junk
./rem
