#!/bin/sh

libpath=`rtai-config --library-dir`

if [ "$libpath" == "" ]; then
echo "ERROR: please set your PATH variable to <rtai-install>/bin"
exit
fi

export LD_LIBRARY_PATH=$libpath:$LD_LIBRARY_PATH

if [ $UID != 0 ]; then SUDO='sudo '; else SUDO=''; fi
echo 
echo "*** SOUND USING FIFO (user) ***"
echo "Press enter to load lxrt module:"
read junk
cd ../..; ./ldmod; cd -
echo 
echo "Now press <enter> to run the RT program:"
read junk
sync
$SUDO ./fifosound
echo 
echo "To remove the modules, press <enter>:"
read junk
./rem
