EXTRA_CFLAGS += -I$(rtai_srctree)/base/include \
		-I$(src)/../../../base/include \
		-I$(src)/../../.. \
		$(rtai_extradef) \
		-D__IN_RTAI__

obj-m += kthreads_preempt_rt.o

kthreads_preempt_rt-objs := $(rtai_objs)
