#!/bin/sh
#!/bin/sh

prefix=`rtai-config --prefix`
arch=`rtai-config --arch`
insmod=/sbin/insmod

MODULES=$prefix/modules

sync
if [ $UID != 0 ]; then SUDO="sudo "; else SUDO=""; fi
echo
echo "*** DIRECT IRQ HANDLING (kernel) ***"
echo "Press <enter> to load modules:"
read junk

if [ "$prefix" == "" ]; then
echo "ERROR: please set your PATH variable to <rtai-install>/bin"
exit
fi

if [ "$arch" = "i386" ]; then
$insmod $MODULES/rtai_hal.ko;
else
$insmod $MODULES/rtai_hal.o
fi

echo
echo "Now start the realtime process <enter> ...."
echo "... <enter> again to end and to remove the modules."
read junk
sync
if (`rtai-config --linux-version | grep -q 2.6`);
then insmod ./dsp_rt.ko;
else insmod ./dsp.o; fi
echo
read junk
./rem
