#!/bin/sh

prefix=`rtai-config --prefix`

if [ "$prefix" == "" ]; then
echo "ERROR: please set your PATH variable to <rtai-install>/bin"
exit
fi

libpath=`rtai-config --library-dir`
export LD_LIBRARY_PATH=$libpath:$LD_LIBRARY_PATH
 
MODULES=$prefix/modules

if [ $UID != 0 ]; then SUDO="sudo "; else SUDO=""; fi
echo
echo "*** A PROCESS BASED USER SPACE INTERRUPT HANDLER ***"
echo "Press <enter> to load modules:"
read junk
cd ../..; ./ldmod; cd -
if (`rtai-config --linux-version | grep -q 2.6`);
then insmod $MODULES/rtai_tasklets.ko; insmod $MODULES/rtai_usi.ko;
else insmod $MODULES/rtai_tasklets.o; insmod $MODULES/rtai_usi.o; fi
echo
echo "Now start the realtime process <enter>."
read junk
sync
$SUDO ./usi_process
echo
echo "Done. Press <enter> to remove the modules."
read junk
./rem
