TARGETS = \
	benchrtdm \
	bitstest \
	forcesoft \
	forked \
	fusion \
	hardsoftsw \
	heaps \
	i386 \
	intertaskmsg \
	latency \
	linux_server \
	master_slave \
	msg_clock \
	netrpc \
	pqueue \
	preempt \
	rt_agent \
	rtdm \
	sem_clock \
	switches \
	tasklets \
	tbx \
	threaded

include ../share/recurse.mk
