#!/bin/sh
if [ $UID != 0 ]; then SUDO="sudo "; else SUDO=""; fi
echo
echo "*** TESTs CONDVARs and BARRIERs (kernel) ***"
echo "Press <enter> to load modules:"
read junk
cd ..; ./ldmod; cd -
echo
echo "Now start the realtime process <enter> and wait for its end:"
read junk
if [`rtai-config --linux-version | grep -q 2.6` -o `rtai-config --linux-version | grep -q 3.`];
then insmod ./condtest_rt.ko;
else insmod ./condtest.o; fi
echo
echo "Done. Press <enter> to remove the modules."
read junk
./rem
