#!/bin/sh
if [ $UID != 0 ]; then SUDO="sudo "; else SUDO=""; fi
echo
echo "*** TESTs RWLOCKs (kernel) ***"
echo "Press <enter> to load modules:"
read junk
cd ..
./ldmod
cd -
sync
echo "Now start the realtime process <enter>."
read junk
if (`rtai-config --linux-version | grep -q 2.6`);
then insmod ./rwlocks_rt.ko;
else insmod ./rwlocks.o; fi
echo
echo "Done. Press <enter> to remove the modules."
read junk
rmmod rwlocks
./rem
