#!/bin/sh
if [ $UID != 0 ]; then SUDO="sudo "; else SUDO=""; fi
echo
echo "*** TESTs MQUEUEs (kernel) ***"
echo "Press <enter> to load modules:"
read junk
cd ..; ./ldmod; cd -
sync
echo
echo "Now start the realtime process <enter>."
read junk
if [`rtai-config --linux-version | grep -q 2.6` -o `rtai-config --linux-version | grep -q 3.`];
then insmod ./mqtest_rt.ko;
else insmod ./mqtest.o; fi
echo
echo "Done. Press <enter> to remove the modules."
read junk
rmmod mqtest
./rem
