// ------------------------------------------------------
// generated by builder.sce: Please do not edit this file
// ------------------------------------------------------

rt_rtai_path = get_absolute_file_path('loader.sce');

link(rt_rtai_path+'librt_rtai.so',['rtsinus','rtsquare','rt_step'],'c');
// remove temp. variables on stack
clear rt_rtai_path;
clear get_file_path;
// ------------------------------------------------------
