EXTRA_CFLAGS += $(shell rtai-config --module-cflags)

obj-m += clock_rt.o cmdclk_rt.o cmdcrn_rt.o dispclk_rt.o

clock_rt-objs := clock.o

cmdclk_rt-objs := cmdclk.o

cmdcrn_rt-objs := cmdcrn.o

dispclk_rt-objs := dispclk.o
