#!/bin/sh
if [ $UID != 0 ]; then SUDO="sudo "; else SUDO=""; fi
echo
echo "*** RESUME A PROCESS FROM INTERRUPT (kernel) ***"
echo "Press <enter> to load modules:"
read junk
cd ../..; ./ldmod; cd -
echo
echo "Now start the realtime process <enter>, <ctrl-C> to end it."
read junk
sync
if [`rtai-config --linux-version | grep -q 2.6` -o `rtai-config --linux-version | grep -q 3.`];
then insmod ./resumefromintr_rt.ko Mode=1;
else insmod ./resumefromintr.o; fi
./display
echo
echo "Done. Press <enter> to remove the modules."
read junk
./rem
