#!/bin/sh
ACLOCAL=aclocal
AUTOMAKE=automake

die() {
	echo
	echo "error: $1";
	echo
	exit -1;
}

echo

echo -n "running libtoolize..."
libtoolize -c --automake
if [ "$?" != "0" ]; then die "running libtoolize"; fi
echo "done"

echo -n "running aclocal..."
if test -r acinclude.m4 ; then
   touch acinclude.m4
   $ACLOCAL
else
   $ACLOCAL -I m4
fi
if [ "$?" != "0" ] ; then die "running aclocal"; fi
echo "done"

echo -n "running autoconf..."
autoconf
if [ "$?" != "0" ]; then die "running autoconf"; fi
echo "done"

echo -n "running autoheader..."
autoheader
if [ "$?" != "0" ]; then die "running autoheader"; fi
echo "done"

echo -n "running automake..."
$AUTOMAKE -a -c
if [ "$?" != "0" ]; then die "running automake"; fi
echo "done"

echo
