#!/bin/sh

die() {
	echo
	echo "error: $1";
	echo
}

echo

echo -n "running libtoolize..."
libtoolize --force --copy --automake
if [ "$?" != "0" ]; then die "running libtoolize"; fi
echo "done"

echo -n "running aclocal..."
aclocal --force -I base/config/autoconf
if [ "$?" != "0" ] ; then die "running aclocal"; fi
echo "done"

echo -n "running autoconf..."
autoconf --force
if [ "$?" != "0" ]; then die "running autoconf"; fi
echo "done"

echo -n "running autoheader..."
autoheader --force
if [ "$?" != "0" ]; then die "running autoheader"; fi
echo "done"

echo -n "running automake..."
automake --force -a -c
if [ "$?" != "0" ]; then die "running automake"; fi
echo "done"

echo
