#!/bin/sh

libpath=`rtai-config --library-dir`

if test "$libpath" = ""; then
echo "ERROR: please set your PATH variable to <rtai-install>/bin"
exit
fi

export LD_LIBRARY_PATH=$libpath:$LD_LIBRARY_PATH

if test $UID != 0; then SUDO="sudo "; else SUDO=""; fi
echo
echo "*** BITSTEST (user) ***"
echo "Press <enter> to load LXRT modules:"
read junk
cd ../; ./ldmod; cd -
echo
echo "Now start the realtime process <enter>:"
read junk
$SUDO ./bitstest
echo
echo "Done. Press <enter> to remove the modules."
read junk
../remod
