EXTRA_CFLAGS += -I$(rtai_srctree)/base/include \
		-I$(src)/../include \
		-I$(src)/../.. \
		$(rtai_extradef) \
		-D_IEEE_LIBM \
		-D_ISOC99_SOURCE \
		-D_SVID_SOURCE \
		-D__IN_RTAI__

obj-m += rtai_math.o

rtai_math-objs := $(rtai_objs)
