#!/bin/sh

libpath=`rtai-config --library-dir`

if test "$libpath" = ""; then
echo "ERROR: please set your PATH variable to <rtai-install>/bin"
exit
fi

export LD_LIBRARY_PATH=$libpath:$LD_LIBRARY_PATH

echo
echo "*** LATENCY MEASUREMENT (user) ***"
echo "Press <enter> to load LXRT modules:"
read junk
cd ..; ./ldmod; cd -
echo
echo "Now start the realtime process <enter> and wait for its end:"
read junk
./latency &
until(`ps -a | grep -q latency`); do sleep 1; done
./display
echo
echo "Done. Press <enter> to remove the modules."
read junk
./rem
