#!/bin/sh

prefix=`rtai-config --prefix`

if [ "$prefix" == "" ]; then
echo "ERROR: please set your PATH variable to <rtai-install>/bin"
exit
fi

libpath=`rtai-config --library-dir`
export LD_LIBRARY_PATH=$libpath:$LD_LIBRARY_PATH

MODULES=$prefix/modules

if [ $UID != 0 ]; then SUDO="sudo "; else SUDO=""; fi
echo
echo "*** TIMERs in USER and KERNEL SPACE COORDINATED THROUGH SHARED MEM ***"
echo "Press <enter> to load modules:"
read junk
cd ..; ./ldmod; cd -
sync
if [`rtai-config --linux-version | grep -q 2.6` -o `rtai-config --linux-version | grep -q 3.`];
then insmod $MODULES/rtai_tasklets.ko; insmod ./kctest_rt.ko;
else insmod $MODULES/rtai_tasklets.o; insmod ./kctest.o; fi
echo
echo "Now start the realtime process <enter> and wait for its end."
read junk
sync
./uctest
echo
echo "Done. Press <enter> to remove the modules."
read junk
./rem
