#!/bin/sh

prefix=`rtai-config --prefix`

if [ "$prefix" == "" ]; then
echo "ERROR: please set your PATH variable to <rtai-install>/bin"
exit
fi

MODULES=$prefix/modules

comedi_dir=`rtai-config --comedi-dir`

COMEDI_DIR=$comedi_dir

libpath=`rtai-config --library-dir`

if [ "$libpath" == "" ]; then
echo "ERROR: please set your PATH variable to <rtai-install>/bin"
exit
fi

export LD_LIBRARY_PATH=$libpath:$LD_LIBRARY_PATH

if [ $UID != 0 ]; then SUDO="sudo "; else SUDO=""; fi
echo
echo "*** COMEDI VERIFICATION OF REMOTE USAGE (user) ***"
echo "Press <enter> to load LXRT modules:"
read junk
#insmod $COMEDI_DIR/comedi.ko
#insmod $COMEDI_DIR/kcomedilib/kcomedilib.ko
#insmod $COMEDI_DIR/drivers/comedi_fc.ko
cd ../; ./ldmod; cd -
insmod $MODULES/rtai_netrpc.ko ThisNode="127.0.0.1";
insmod kcomedi_rt.ko
echo
echo "Now start the realtime process <enter>:"
read junk
$SUDO ./rmtest
echo
echo "Done. Press <enter> to remove the modules."
read junk
./rem
