#!/bin/sh

prefix=`rtai-config --prefix`
MODULES=$prefix/modules

if [ $UID != 0 ]; then SUDO="sudo "; else SUDO=""; fi
echo
echo "*** RESUME A PROCESS FROM INTERRUPT (kernel) ***"
echo "Press <enter> to load modules:"
read junk
echo
echo "Now start the realtime process <enter>, <ctrl-C> to end it."
read junk
sync
if (`rtai-config --linux-version | grep -q 2.6`);
then
insmod $MODULES/rtai_hal.ko IsolCpusMask=2;
insmod $MODULES/rtai_ksched.ko;
insmod $MODULES/rtai_sem.ko;
insmod $MODULES/rtai_msg.ko;
insmod $MODULES/rtai_rtdm.ko;
insmod ./resumefromintr_rt.ko;
else
insmod $MODULES/rtai_hal.o IsolCpusMask=0;
insmod $MODULES/rtai_ksched.o;
insmod $MODULES/rtai_sem.o;
insmod $MODULES/rtai_msg.o;
insmod $MODULES/rtai_rtdm.o;
insmod ./resumefromintr.o;
fi
./display
echo
echo "Done. Press <enter> to remove the modules."
read junk
./rem
