#!/bin/sh

libpath=`rtai-config --library-dir`

if [ "$libpath" == "" ]; then
echo "ERROR: please set your PATH variable to <rtai-install>/bin"
exit
fi

export LD_LIBRARY_PATH=$libpath:$LD_LIBRARY_PATH

if [ $UID != 0 ]; then SUDO="sudo "; else SUDO=""; fi
echo
echo "*** USER SPACE TASKs SWITCHING TIME (user) ***"
echo "Press <enter> to load LXRT modules:"
read junk
cd ../; ./ldmod; cd -
echo
echo "Now start the realtime process <enter>:"
read junk
$SUDO ./switches
echo
echo "Done. Press <enter> to remove the modules."
read junk
../remod
