#!/bin/sh

libpath=`rtai-config --library-dir`

if [ "$libpath" == "" ]; then
echo "ERROR: please set your PATH variable to <rtai-install>/bin"
exit
fi

export LD_LIBRARY_PATH=$libpath:$LD_LIBRARY_PATH

if [ $UID != 0 ]; then SUDO="sudo "; else SUDO=""; fi
echo
echo "*** ANOTHER INTERRUPT LATENCY MONITOR  ***"
echo "Press <enter> to load modules:"
read junk
cd ..; ./ldmod; cd -
echo
echo "Now start the realtime process <enter> and wait for its end."
read junk
sync
if [`rtai-config --linux-version | grep -q 2.6` -o `rtai-config --linux-version | grep -q 3.`];
then insmod ./intrlat_rt.ko;
else insmod ./intrlat.o; fi
echo
echo "Press <enter> to remove the module."
read junk
./rem
