EXTRA_CFLAGS += $(shell rtai-config --module-cflags)

obj-m += tut01-skeleton-drv_rt.o tut02-skeleton-drv_rt.o

tut01-skeleton-drv_rt-objs := tut01-skeleton-drv.o

tut02-skeleton-drv_rt-objs := tut02-skeleton-drv.o
