#!/bin/sh

prefix=`rtai-config --prefix`

if test "$prefix" = ""; then
echo "ERROR: please set your PATH variable to <rtai-install>/bin"
exit
fi

MODULES=$prefix/modules

libpath=`rtai-config --library-dir`

if test "$libpath" = ""; then
echo "ERROR: please set your PATH variable to <rtai-install>/bin"
exit
fi

export LD_LIBRARY_PATH=$libpath:$LD_LIBRARY_PATH

if test $UID -ne 0; then SUDO="sudo "; else SUDO=""; fi
echo
echo "*** HARD USER SPACE CLIENT/SERVER THROUGH A KERNEL AGENT ***"
echo "Press <enter> to load modules:"
read junk
cd ..; ./ldmod; cd -
if (`rtai-config --linux-version | grep -q 2.6`);
then
insmod $MODULES/rtai_rtdm.ko
else
insmod $MODULES/rtai_rtdm.o
fi
echo
echo "Now start the realtime process <enter> and wait for its end."
read junk
sync
if (`rtai-config --linux-version | grep -q 2.6`);
then insmod ./tut01-skeleton-drv_rt.ko;
else insmod ./tut01-skeleton-drv.o; fi
$SUDO ./tut01-skeleton-app
echo
echo "Done. Press <enter> to remove the modules."
read junk
./rem
