#!/bin/sh

libpath=`rtai-config --library-dir`

if [ "$libpath" == "" ]; then
echo "ERROR: please set your PATH variable to <rtai-install>/bin"
exit
fi

export LD_LIBRARY_PATH=$libpath:$LD_LIBRARY_PATH

if [ $UID != 0 ]; then SUDO="sudo "; else SUDO=""; fi
echo
echo "Press <enter> to load LXRT modules:"
read junk
cd ..; ./ldmod; cd -
echo
echo "*** PRIO INHERITHANCE FOR MSGs, AS AT RTAI-LAB BEGINNING (user) ***"
echo "Now start the realtime process:"
read junk
$SUDO ./inhermsg $1 $2 $3
echo
echo "Done. Press <enter> to remove the modules."
read junk
../remod
