#!/bin/sh
if [ $UID != 0 ]; then SUDO="sudo "; else SUDO=""; fi
echo
echo "*** MQUEUEs (kernel) ***"
echo "Press <enter> to load modules:"
read junk
cd ..; ./ldmod; cd -
echo
echo "Now start the realtime process <enter> and wait for its end."
read junk
sync
if [`rtai-config --linux-version | grep -q 2.6` -o `rtai-config --linux-version | grep -q 3.`];
then insmod ./pqueue_rt.ko; insmod ./mod_stuff_rt.ko;
else insmod ./pqueue_rt.o; insmod ./mod_stuff_rt.o; fi
echo
echo "Done. Press <enter> to remove the modules."
read junk
./rem
