EXTRA_CFLAGS += -I$(rtai_srctree)/base/include \
		-I$(rtai_srctree)/addons/rtdm \
		-I$(src)/../include \
		-I$(src)/../.. \
		$(rtai_extradef) \
		-D__IN_RTAI__

obj-m += $(rtai_target).o

rtai_tmpsched-objs := $(rtai_objs)

rtai_sched-objs := $(rtai_objs)

rtai_lxrt-objs := $(rtai_objs)

