#!/bin/sh

prefix=`rtai-config --prefix`

if [ "$prefix" == "" ]; then
echo "ERROR: please set your PATH variable to <rtai-install>/bin"
exit
fi

libpath=`rtai-config --library-dir`
export LD_LIBRARY_PATH=$libpath:$LD_LIBRARY_PATH

MODULES=$prefix/modules

if [ $UID != 0 ]; then SUDO="sudo "; else SUDO=""; fi
echo
echo "*** RTNET SIMPLE BASIC TESTS  (user) ***"
echo "Press <enter> to load LXRT modules:"
read junk
cd ..; ./ldmod; cd -
insmod $MODULES/rtai_rtdm.ko
./rtnet_up
echo
echo "Now start the realtime process <enter> and wait for its end:"
read junk
/usr/rtnet/examples/rtai/rtnet_ifs
/usr/rtnet/examples/rtai/simpleserver 5000 &
sleep 0.05
/usr/rtnet/examples/rtai/simpleclient 5000 127.0.0.1 5000
/usr/rtnet/examples/rtai/simpleclient 5000 127.0.0.1 5000 50 50
echo
echo "Done. Press <enter> to remove the modules."
read junk
./rem
