#!/bin/sh

prefix=`rtai-config --prefix`

if [ "$prefix" == "" ]; then
echo "ERROR: please set your PATH variable to <rtai-install>/bin"
exit
fi

libpath=`rtai-config --library-dir`
export LD_LIBRARY_PATH=$libpath:$LD_LIBRARY_PATH

MODULES=$prefix/modules

if [ $UID != 0 ]; then SUDO="sudo "; else SUDO=""; fi
echo
echo "*** SOUND USING REMOTE INTERTASK MSGes (user) ***"
echo "Press <enter> to load modules:"
read junk
cd ../..; ./ldmod; cd -
sync
if (`rtai-config --linux-version | grep -q 2.6`);
then insmod $MODULES/rtai_netrpc.ko ThisNode="131.175.154.67" #"127.0.0.1";
else insmod $MODULES/rtai_netrpc.o ThisNode="127.0.0.1"; fi
echo
echo "Now start the realtime process <enter>,"
echo "Press <enter> when you want to end it."
read junk
$SUDO ./player SpkNode="131.175.154.223" #"127.0.0.1"
echo
echo "Done. Press <enter> to remove the modules."
read junk
./rem
